server:
  port: 8761

# 安全认证的配置
security:
  basic:
    enabled: true
  user:
    name: qtb  # 用户名
    password: jxtb   # 用户密码

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/